version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    environment:
      - BROWSERSTACK_USERNAME: orlandoavila_SaKnUC
      - BROWSERSTACK_ACCESS_KEY: wpUp3j8EbKrHdvrweUxk
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run Appium tests
          command: |
            chmod +x gradlew
            ./gradlew clean test --tests LoginRunner
      - store_artifacts:
          path: test-output/HtmlReport
          destination: extent-report
      - store_test_results:
          path: test-output/HtmlReport

workflows:
  version: 2
  test-build:
    jobs:
      - build